import './globals.css'
import { Inter } from 'next/font/google'
import { profile } from '@/data/profile'

const inter = Inter({ subsets: ['latin'], display: 'swap', variable: '--font-inter' })

// Shown in the browser tab and, more importantly, on the preview card that
// LinkedIn, Slack and messaging apps render when this URL is pasted. Without
// openGraph the card is a bare grey rectangle, which is how most people will
// first see this site. The image itself is generated by opengraph-image.js;
// Next wires it into both openGraph and twitter automatically.
const title = `${profile.name} | Portfolio`
const cardTitle = `${profile.name} | Full-stack developer`

export const metadata = {
  metadataBase: new URL(profile.canonicalUrl),
  title,
  description: profile.tagline,
  authors: [{ name: profile.name, url: profile.canonicalUrl }],
  creator: profile.name,
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    url: profile.canonicalUrl,
    siteName: title,
    title: cardTitle,
    description: profile.tagline,
    locale: 'en_AU',
  },
  twitter: {
    card: 'summary_large_image',
    title: cardTitle,
    description: profile.tagline,
  },
  robots: { index: true, follow: true },
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body className="bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-100 antialiased">
        <script dangerouslySetInnerHTML={{ __html: "document.documentElement.classList.add('js')" }} />
        {children}
      </body>
    </html>
  )
}
